trigger:
- develop
- qa

resources:
  repositories:
    - repository: templates
      type: git
      name: DevOps
stages:
  - template: compileback.yml@templates
    parameters:
      dfile: "src/hexagonal.api/Dockerfile"
      micro: "Base"
      appfolder: "src/hexagonal.api/"

      ${{ if eq(variables['Build.SourceBranchName'], 'develop') }}:
        ambiente: "develop"
        pool: "LinuxDevUbuntu"
        conregistry: "RegistryDevUbuntu"
        targetfiles: "appsettings.Development.json"
      ${{ if eq(variables['Build.SourceBranchName'], 'qa') }}:
        ambiente: "qa"
        pool: "Linux Qa"
        conregistry: "RegistryQA"
        targetfiles: "appsettings.QA.json"